# Generated by Django 4.2.16 on 2026-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='canvas_user_precreated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
