# Generated by Django 4.2.16 on 2026-04-17 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('form_created', 'Form created'), ('form_updated', 'Form updated'), ('form_published', 'Form published'), ('form_closed', 'Form closed'), ('form_deleted', 'Form deleted'), ('sub_approved', 'Submission approved'), ('sub_rejected', 'Submission rejected'), ('sub_resynced', 'Submission re-synced'), ('canvas_synced', 'Canvas sync succeeded'), ('canvas_failed', 'Canvas sync failed'), ('role_changed', 'User role changed'), ('user_created', 'User created')], max_length=40)),
                ('target_type', models.CharField(blank=True, help_text='e.g. Form, Submission, User', max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='Human-readable target description', max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Extra context e.g. old/new role')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
