# Generated by Django 4.2.16 on 2026-04-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('form_created', 'Form created'), ('form_updated', 'Form updated'), ('form_published', 'Form published'), ('form_closed', 'Form closed'), ('form_deleted', 'Form deleted'), ('sub_approved', 'Submission approved'), ('sub_rejected', 'Submission rejected'), ('sub_unrejected', 'Submission rejection reverted'), ('sub_resynced', 'Submission re-synced'), ('canvas_synced', 'Canvas sync succeeded'), ('canvas_failed', 'Canvas sync failed'), ('role_changed', 'User role changed'), ('user_created', 'User created')], max_length=40),
        ),
    ]
